name: heureka
author: Heureka fan
description: Heureka fan pokus
version: 0.1.0
dependencies:
  angular: ^5.0.0
dev_dependencies:
  build_runner: ^1.0.0
  build_test: ^0.10.2
  build_web_compilers: ^0.4.0
